title: Thomas Kimmel # your name (or website title) here
logo: "images/thomas_pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Urban Planning and Spatial Analytics
  <br><br>
  MUSA 620 Final Project
  <br><br>
  <a href="https://www.linkedin.com/in/thomas-kimmel-29a523134/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
plot: "images/nbcrime.png"
